backend:
  name: github
  repo: nathanborges546-sketch/Portfolio-Nathan-Borges 
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data de Publicação", name: "pubDate", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Rascunho", name: "draft", widget: "boolean", default: false}
      - {label: "Corpo do Artigo", name: "body", widget: "markdown"}
